export const CLASS_NAMES: {
    ARCHER: 'ARCHER',
    BERSERKER: 'BERSERKER',
    DEFFENDER: 'DEFFENDER',
    FENCER: 'FENCER',
    NINJA: 'NINJA',
    PALADIN: 'PALADIN',
    SNIPER: 'SNIPER',
    SOLDIER: 'SOLDIER',
    THIEVE: 'THIEVE'
} = {
    ARCHER: 'ARCHER',
    BERSERKER: 'BERSERKER',
    DEFFENDER: 'DEFFENDER',
    FENCER: 'FENCER',
    NINJA: 'NINJA',
    PALADIN: 'PALADIN',
    SNIPER: 'SNIPER',
    SOLDIER: 'SOLDIER',
    THIEVE: 'THIEVE'
}